//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rights.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int IdBonus { get; set; }
        public string BonusName { get; set; }
        public Nullable<int> IdOrganization { get; set; }
        public string Description { get; set; }
    
        public virtual Organizations Organizations { get; set; }
    }
}
