//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rights.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteePayment
    {
        public int IdCommitteePayment { get; set; }
        public int IdStaff { get; set; }
        public string PaymentDate { get; set; }
        public string PaymentAmount { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
