//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rights.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizations
    {
        public int IdOrganization { get; set; }
        public string NameOrganization { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
