//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rights.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialPrograms
    {
        public int IdPrograms { get; set; }
        public string ProgramName { get; set; }
        public string ProgramDiscription { get; set; }
        public int IdCommitte { get; set; }
    
        public virtual Committee Committee { get; set; }
    }
}
