//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rights.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solutions
    {
        public int IdSolutions { get; set; }
        public string Discription { get; set; }
        public int IdMeetings { get; set; }
    
        public virtual Meetings Meetings { get; set; }
    }
}
